// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Taishakuten;

#nullable disable

namespace Taishakuten.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220302215845_AddGuilds")]
    partial class AddGuilds
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Taishakuten.Entities.Guild", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<bool>("ScanEnabled")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("Taishakuten.Entities.Reminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("At")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("Channel")
                        .HasColumnType("bigint unsigned");

                    b.Property<bool>("Fired")
                        .HasColumnType("tinyint(1)");

                    b.Property<ulong>("Guild")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("Snoozes")
                        .HasColumnType("int");

                    b.Property<ulong>("User")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("User", "At");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("Taishakuten.Entities.Welcome", b =>
                {
                    b.Property<ulong>("Guild")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Body")
                        .HasMaxLength(4096)
                        .HasColumnType("varchar(4096)");

                    b.Property<ulong>("Channel")
                        .HasColumnType("bigint unsigned");

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<bool>("Mention")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Title")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Guild");

                    b.ToTable("Welcomes");
                });
#pragma warning restore 612, 618
        }
    }
}
